CUDA_VISIBLE_DEVICES=0 nohup python3 /mnt/bn/data-tns-live-llm/leon/Cherry_LLM/training/stanford_alpaca/train_qlora.py   --model_name_or_path /mnt/bn/data-tns-live-llm/leon/datasets/llama-3-8b-bnb-4bit/   --data_path /mnt/bn/data-tns-live-llm/leon/datasets/merged_data/random_code.parquet   --per_device_train_batch_size 16   --gradient_accumulation_steps 2   --eval_strategy no   --num_train_epochs 2   --learning_rate 2e-5   --warmup_ratio 0.03   --output_dir /mnt/bn/data-tns-live-llm/leon/datasets/warmup_random_code   --logging_steps 100 --save_strategy "epoch" --bf16 --unsloth 1 --merge 1 > out/warm_random_code.out &

CUDA_VISIBLE_DEVICES=1 nohup python3 /mnt/bn/data-tns-live-llm/leon/Cherry_LLM/training/stanford_alpaca/train_qlora.py   --model_name_or_path /mnt/bn/data-tns-live-llm/leon/datasets/llama-3-8b-bnb-4bit/   --data_path /mnt/bn/data-tns-live-llm/leon/datasets/merged_data/random_code.parquet   --per_device_train_batch_size 16   --gradient_accumulation_steps 2   --eval_strategy no   --num_train_epochs 2   --learning_rate 2e-5   --warmup_ratio 0.03   --output_dir /mnt/bn/data-tns-live-llm/leon/datasets/warmuped_random_med   --logging_steps 100 --save_strategy "epoch" --bf16 --unsloth 1 --merge 1 > out/warm_random_med.out &

sleep 3600

CUDA_VISIBLE_DEVICES=0 nohup python3 /mnt/bn/data-tns-live-llm/leon/Cherry_LLM/training/stanford_alpaca/train_qlora.py   --model_name_or_path /mnt/bn/data-tns-live-llm/leon/datasets/llama-3-8b-bnb-4bit/   --data_path /mnt/bn/data-tns-live-llm/leon/datasets/merged_data/random_code.parquet   --per_device_train_batch_size 16   --gradient_accumulation_steps 2   --eval_strategy no   --num_train_epochs 2   --learning_rate 2e-5   --warmup_ratio 0.03   --output_dir /mnt/bn/data-tns-live-llm/leon/datasets/warmuped_random_fin   --logging_steps 100 --save_strategy "epoch" --bf16 --unsloth 1 --merge 1 > out/warm_random_fin.out &

CUDA_VISIBLE_DEVICES=1 nohup python3 /mnt/bn/data-tns-live-llm/leon/Cherry_LLM/training/stanford_alpaca/train_qlora.py   --model_name_or_path /mnt/bn/data-tns-live-llm/leon/datasets/llama-3-8b-bnb-4bit/   --data_path /mnt/bn/data-tns-live-llm/leon/datasets/merged_data/random_code.parquet   --per_device_train_batch_size 16   --gradient_accumulation_steps 2   --eval_strategy no   --num_train_epochs 2   --learning_rate 2e-5   --warmup_ratio 0.03   --output_dir /mnt/bn/data-tns-live-llm/leon/datasets/warmuped_random_math   --logging_steps 100 --save_strategy "epoch" --bf16 --unsloth 1 --merge 1 > out/warm_random_math.out &
